// Code generated by MockGen. DO NOT EDIT.
// Source: logger.go

// Package dBlogger_mock is a generated GoMock package.
package dBlogger_mock

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// LogRegistration mocks base method.
func (m *MockInterface) LogRegistration(userID int64, name string, time time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogRegistration", userID, name, time)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogRegistration indicates an expected call of LogRegistration.
func (mr *MockInterfaceMockRecorder) LogRegistration(userID, name, time interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRegistration", reflect.TypeOf((*MockInterface)(nil).LogRegistration), userID, name, time)
}
